name: idm
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - pytorch=2.3.0=py3.12_cuda12.4_cudnn9.0.0_0
  - pytorch-cuda=12.4
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - pip=24.0

  - pip:
      - accelerate==0.30.1
      - torchmetrics==1.3.1
      - tqdm==4.66.2
      - transformers==4.40.0
      - diffusers==0.27.2
      - einops==0.7.0
      - bitsandbytes==0.42.0
      - scipy==1.12.0
      - opencv-python==4.9.0.80
      - gradio==4.24.0
      - fvcore==0.1.5.post20240519
      - cloudpickle==2.2.1
      - omegaconf==2.3.0
      - pycocotools==2.0.7
      - basicsr==1.4.2
      - av==11.0.0
      - onnxruntime==1.17.0
      - safetensors==0.4.2
      - xformers==0.0.23.post1
      - huggingface-hub>=0.20.2
